### ISSUE TITLE
Installing colcon and colcon-ros-bundle on Ubuntu 16.04

### ISSUE THREAD

**Issue by bsamadi** [colcon/colcon-ros-bundle#15]
When I run the following command on Ubuntu 16.04:

`pip3 install -U colcon-common-extensions colcon-ros-bundle`

I get this error:
AssertionError: colcon-ros-bundle .dist-info directory not found

What am I missing?

**Comment by dirk-thomas** [comment]
I am not sure if you have seen the [ROS support guidelines](http://wiki.ros.org/Support) but cross posting the same question in multiple locations is consider bad etiquette: https://answers.ros.org/question/319937/installing-colcon-and-colcon-ros-bundle-on-ubuntu-1604/

Therefore I am going to close this ticket as a duplicate.

**Comment by bsamadi** [comment]
Please move your answer to answers.ros.org. This is GitHub.

**Comment by bsamadi** [comment]
I don't see anything about GitHub in the ROS support guidelines on answers.ros.org. Where do you think I can find someone who can help?

**Comment by dirk-thomas** [comment]
Maybe one of the authors of this package (e.g. @murphm8) will be able to answer your question. on answers.ros.org.
