### ISSUE TITLE
Installing colcon and colcon-ros-bundle on Ubuntu 18.04

### ISSUE THREAD

**Issue by bsamadi** [colcon/colcon-ros-bundle#16]
When I run the following command on Ubuntu 16.04:

pip3 install -U colcon-common-extensions colcon-ros-bundle

I get these errors:
Failed building wheel for colcon-ros-bundle
Failed building wheel for colcon-bundle
Failed building wheel for EmPy
Failed building wheel for distlib
error: invalid command 'bdist_wheel'
Failed building wheel for PyYAML

What am I missing?

**Comment by murphm8** [comment]
Are you installing on 18.04 or 16.04?

I wouldn't expect these errors to happen. Can you provide the output of `pip freeze`?

**Comment by emersonknapp** [comment]
Closing as stale - original reporter can reopen with more info.
