### ISSUE TITLE
Package conflicts with latest rosdep versions

### ISSUE THREAD

**Issue by cottsay** [colcon/colcon-ros-bundle#19]
The `setup.cfg` __requires__ an older version of `rosdep` than is currently available (0.15.2):
```
install_requires =
    colcon-bundle>=0.0.10
    colcon-ros>=0.3.5
    rosdep<=0.14.0
    setuptools>=30.3.0
```

Is this conditional backwards, or is there a reason that this package requires the older version?

**Comment by AAlon** [comment]
Thanks - this has been solved by https://github.com/colcon/colcon-ros-bundle/pull/29
